#!/usr/bin/env python3
import sys
with open(sys.argv[1], "rb") as infile:
	inarr = infile.read()
beginindex = 0
size = 0
i = 0
while True:
	beginindex = inarr.find(bytes("dex\n035", "utf-8"), beginindex + size)
	if beginindex < 0:
		break
	sizeindex = beginindex + 8 + 4 + 20
	size = inarr[sizeindex] | inarr[sizeindex + 1] << 8 | inarr[sizeindex + 2] << 16 | inarr[sizeindex + 3] << 24
	with open(sys.argv[2] + "_" + str(i) + ".dex", "wb") as outfile:
		outfile.write(inarr[beginindex:beginindex + size])
	i += 1
